version: '2'

services:
  safety_gear_db:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    container_name: safety_gear_db
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safety_gear_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_LOWER_CASE_TABLE_NAMES: 2

  safety_gear:
    depends_on:
      - safety_gear_db
    image: wordpress:php8.0
    container_name: safety_gear
    ports:
      - "80:80"
    restart: always
    links:
      - safety_gear_db:mysql
    volumes:
      - ./public_html:/var/www/html

  phpmyadmin:
    depends_on:
      - safety_gear_db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: "localhost"
      PMA_USER: "user"
      PMA_PASSWORD: "user"

      ## TODO: permission missing for public_html
      ## MYSQL_LOWER_CASE_TABLE_NAMES error :: remove data folder
      ## 5MB file upload permission
      #phpmyadmin