services:
  safety_gear_db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safety_gear_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  safety_gear:
    depends_on:
      - safety_gear_db
    image: wordpress:php8.0
    container_name: safety_gear
    ports:
      - "443:443"  # Expose port 443 for HTTPS
    restart: always
    links:
      - safety_gear_db:mysql
    volumes:
      - ../public_html:/var/www/html
      - /etc/ssl/certs/greenko_wildcard.crt:/etc/ssl/certs/greenko_wildcard.crt
      - /etc/ssl/private/greenko_wildcard.key:/etc/ssl/private/greenko_wildcard.key
      - /etc/ssl/certs/greenko_wildcard_bundle.crt:/etc/ssl/certs/greenko_wildcard_bundle.crt
    environment:
      - APACHE_SSL=enabled
    entrypoint: /bin/bash -c "a2enmod ssl && a2ensite default-ssl && apache2ctl -D FOREGROUND"

volumes:
  db_data: